use userdb;

delete from AccountContact where uid > 0 and contact_id > 0;
delete from UserScout where uid > 0;
delete from UserContact where contact_id > 0;
delete from UserAccount where uid > 0;
delete from Permission where perm_id > 0;

insert into Permission values(101, 'scout', 1);
insert into Permission values(202, 'adult', 2);
insert into Permission values(303, 'webmaster', 3);
insert into Permission values(404, 'adultadmin', 4);

insert into UserAccount values(1, 'user1', 'user1', 101);
insert into UserAccount values(2, 'user2', 'user2', 101);
insert into UserAccount values(3, 'webmaster', 'webmaster', 303);
insert into UserAccount values(4, 'adult1', 'adult1', 202);
insert into UserAccount values(5, 'adult2', 'adult2', 202);
insert into UserAccount values(6, 'adultadmin', 'adultadmin', 404);
insert into UserAccount values(7, 'henry.frye', 'gang78hug', 202);
insert into UserAccount values(8, 'mark.newton', 'kenneled', 202);
insert into UserAccount values(9, 'zack.powell', '42days', 202);
insert into UserAccount values(10, 'samuel.aston', 'scouts&more', 202);
insert into UserAccount values(11, 'johnathon.weed', 'floors4me', 202);
insert into UserAccount values(12, 'marry.kennrick', 'Down!', 202);
insert into UserAccount values(13, 'frank.hammond', 'JurrasicPark', 101);
insert into UserAccount values(14, 'connor.smith', 'WeBelong', 101);
insert into UserAccount values(15, 'isaac.mabie', 'whodat?', 101);
insert into UserAccount values(16, 'bernie.johnson', 'html', 101);
insert into UserAccount values(17, 'greg.sanders', 'eagleseeker', 101);
insert into UserAccount values(18, 'adam.danvers', '23ravenmen', 101);
insert into UserAccount values(19, 'xander.york', 'downdownwego', 101);
insert into UserAccount values(20, 'carl.pilgrim', 'yesturday', 101);
insert into UserAccount values(21, 'tyler.duns', 'Password69', 101);
insert into UserAccount values(22, 'rodger.wensforth', 'idonotremember', 202);
insert into UserAccount values(23, 'dan.hucker', 'whatpassword', 202);
insert into UserAccount values(24, 'sarah.aston', '12345', 202);
insert into UserAccount values(25, 'elizabeth.weed', 'NowYouSeeMeNow123!', 202);
insert into UserAccount values(26, 'bruce.mabie', 'Notsof@st', 202);
insert into UserAccount values(27, 'marcus.smith', 'itisfish', 202);
insert into UserAccount values(28, 'fred.weed', 'camping', 101);
insert into UserAccount values(29, 'chris.hucker', 'greysquirrel', 101);
insert into UserAccount values(30, 'max.mabie', 'Livn2theM@x!', 101);
insert into UserAccount values(31, 'bob.kennrick', 'sheep', 101);
insert into UserAccount values(32, 'george.aston', 'barnicles', 101);
insert into UserAccount values(33, 'zack.aston', '122planes', 101);
insert into UserAccount values(34, 'hank.frye', '2cold4you', 101);
insert into UserAccount values(35, 'peter.newton', '2gravity', 101);
insert into UserAccount values(36, 'talyer.powell', 'stone78', 101);
insert into UserAccount values(37, 'david.newton', 'apple', 101);
insert into UserAccount values(38, 'jessie.smith', 'jessiejames', 101);
insert into UserAccount values(39, 'nico.banner', 'deadmaster', 101);
insert into UserAccount values(40, 'oliver.parker', 'spiders', 101);
insert into UserAccount values(41, 'ryan.kent', '1fish2fish', 101);
insert into UserAccount values(42, 'evan.baggins', 'evilbags3', 101);
insert into UserAccount values(43, 'sam.wayne', 'sam232', 101);
insert into UserAccount values(44, 'ben.alan', 'bentheman', 101);
insert into UserAccount values(45, 'tyler.hallaway', 'hallways', 101);

insert into UserContact values(11, 'email');
insert into UserContact values(22, 'phone');

insert into AccountContact values(1, 11, 'user1@troop3.com');
insert into AccountContact values(2, 11, 'user2@troop3.com');
insert into AccountContact values(3, 11, 'webmaster@troop3.com');
insert into AccountContact values(4, 11, 'adult1@troop3.com');
insert into AccountContact values(5, 11, 'adult2@troop3.com');
insert into AccountContact values(6, 11, 'adultadmin@troop3.com');
insert into AccountContact values(7, 11, 'frye@verizon.net');
insert into AccountContact values(8, 11, 'newton@comcast.com');
insert into AccountContact values(9, 11, 'powell@yahoo.com');
insert into AccountContact values(10, 11, 'aston@verizon.net');
insert into AccountContact values(11, 11, 'weed@gmail.com');
insert into AccountContact values(12, 11, 'kennrick@hotmail.com');
insert into AccountContact values(13, 11, 'hammond@comcast.com');
insert into AccountContact values(14, 11, 'smith@gmail.com');
insert into AccountContact values(15, 11, 'mabie@verizon.net');
insert into AccountContact values(16, 11, 'johnson@verizon.net');
insert into AccountContact values(17, 11, 'sanders@comcast.com');
insert into AccountContact values(18, 11, 'danvers@hotmail.com');
insert into AccountContact values(19, 11, 'york@yahoo.com');
insert into AccountContact values(20, 11, 'pilgrim@yahoo.com');
insert into AccountContact values(21, 11, 'duns@gmail.com');
insert into AccountContact values(22, 11, 'wensforth@verizon.net');
insert into AccountContact values(23, 11, 'hucker@gmail.com');
insert into AccountContact values(24, 11, 'aston@comcast.net');
insert into AccountContact values(25, 11, 'weed@hotmail.com');
insert into AccountContact values(26, 11, 'whereme@comcast.com');
insert into AccountContact values(27, 11, 'hunter@verizon.net');
insert into AccountContact values(28, 11, 'sleepyman45@yahoo.com');
insert into AccountContact values(29, 11, 'cornhucker@gmail.com');
insert into AccountContact values(30, 11, 'questionmark@comcast.com');
insert into AccountContact values(31, 11, 'raidBoss127@hotmal.com');
insert into AccountContact values(32, 11, 'skyflyer34@yahoo.com');
insert into AccountContact values(33, 11, 'plane.lord@yahoo.com');
insert into AccountContact values(34, 11, 'friggidMaster@gmail.com');
insert into AccountContact values(35, 11, 'apple.picker@hotmail.com');
insert into AccountContact values(36, 11, 'stoneGuard@yahoo.com');
insert into AccountContact values(37, 11, 'physicsGuy28@comcast.com');
insert into AccountContact values(38, 11, 'normaldude231@verizon.net');
insert into AccountContact values(39, 11, 'deadwalker@gmail.com');
insert into AccountContact values(40, 11, 'spiderman@comcast.com');
insert into AccountContact values(41, 11, 'superman@verizon.net');
insert into AccountContact values(42, 11, 'thehobbit@gmail.com');
insert into AccountContact values(43, 11, 'millionare@hotmail.com');
insert into AccountContact values(44, 11, 'goshmyluck@yahoo.com');
insert into AccountContact values(45, 11, 'longesthallway@yahoo.com');

insert into UserScout values(7, 1);
insert into UserScout values(8, 2);
insert into UserScout values(9, 3);
insert into UserScout values(10, 4);
insert into UserScout values(11, 5);
insert into UserScout values(12, 6);
insert into UserScout values(13, 7);
insert into UserScout values(14, 8);
insert into UserScout values(15, 9);
insert into UserScout values(16, 10);
insert into UserScout values(17, 11);
insert into UserScout values(18, 12);
insert into UserScout values(19, 13);
insert into UserScout values(20, 14);
insert into UserScout values(21, 15);
insert into UserScout values(22, 16);
insert into UserScout values(23, 17);
insert into UserScout values(24, 18);
insert into UserScout values(25, 19);
insert into UserScout values(26, 20);
insert into UserScout values(27, 21);
insert into UserScout values(28, 22);
insert into UserScout values(29, 23);
insert into UserScout values(30, 24);
insert into UserScout values(31, 25);
insert into UserScout values(32, 26);
insert into UserScout values(33, 27);
insert into UserScout values(34, 28);
insert into UserScout values(35, 29);
insert into UserScout values(36, 30);
insert into UserScout values(37, 31);
insert into UserScout values(38, 32);
insert into UserScout values(39, 33);
insert into UserScout values(40, 34);
insert into UserScout values(41, 35);
insert into UserScout values(42, 36);
insert into UserScout values(43, 37);
insert into UserScout values(44, 38);
insert into UserScout values(45, 39);

select * from UserAccount;
select * from UserContact;
select * from UserScout;
select * from AccountContact;
select * from Permission;
