<!--//footer for the home page-->
<div id="footer">
	<div id="footer_nav">
		<a href="./php/about.php">About Us</a>
		<a href="./php/contact.php">Contact Us</a>
		<a href="./php/terms.php">Terms of Use Policy</a>
		<a href="./php/privacy.php">Privacy Policy</a>
		<a href="./php/site_map.php">Site Map</a>
	</div>
	
	<div id="closing">
		Troop 3 Burlington &bull; Boy Scouts of America &bull; Champlain College
	</div>
</div>
</div>
</body>
</html>