<!--//footer for the pages in the php folder-->
<div id="footer">
	<div id="footer_nav">
		<a href="about.php">About Us</a>
		<a href="contact.php">Contact Us</a>
		<a href="terms.php">Terms of Use Policy</a>
		<a href="privacy.php">Privacy Policy</a>
		<a href="site_map.php">Site Map</a>
	</div>
	
	<div id="closing">
		Troop 3 Burlington &bull; Boy Scouts of America &bull; Champlain College
	</div>
</div>
</div>
</body>
</html>